# Generated by Django 2.1.15 on 2022-11-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' SOME STRING', max_length=30)),
                ('apellidoP', models.CharField(default=' SOME STRING', max_length=30)),
                ('rut', models.CharField(default=' SOME STRING', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' SOME STRING', max_length=30)),
                ('unidad', models.CharField(default=' SOME STRING', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' SOME STRING', max_length=30)),
                ('capacidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' SOME STRING', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' SOME STRING', max_length=30)),
                ('tiempoPreparacionMin', models.IntegerField(default=0)),
                ('id_ingrediente1', models.IntegerField(default=0)),
                ('id_ingrediente2', models.IntegerField(default=0)),
                ('id_ingrediente3', models.IntegerField(default=0)),
                ('id_ingrediente4', models.IntegerField(default=0)),
                ('id_ingrediente5', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' SOME STRING', max_length=30)),
                ('direccion', models.CharField(default=' SOME STRING', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' SOME STRING', max_length=30)),
                ('apellidoP', models.CharField(default=' SOME STRING', max_length=30)),
                ('rut', models.CharField(default=' SOME STRING', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fact_comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(default=0)),
                ('id_mesa', models.IntegerField(default=0)),
                ('id_usuario', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fact_comandaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factcom', models.IntegerField(default=0)),
                ('id_comanda', models.IntegerField(default=0)),
                ('id_cliente', models.IntegerField(default=0)),
                ('id_plato', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Log_acceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
