# Generated by Django 2.1.15 on 2022-11-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='UnidadBebida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='id_bebida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='id_otros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='id_postre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='precioBebida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='precioPostre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='preciootros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='totalBebida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='totalOtros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='totalPlato',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='totalPostre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='unidadPlato',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='unidadPostre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact_comandadetalle',
            name='unidadotros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log_acceso',
            name='fecha',
            field=models.DateTimeField(default=0),
        ),
        migrations.AddField(
            model_name='log_acceso',
            name='fechafin',
            field=models.DateTimeField(default=0),
        ),
        migrations.AddField(
            model_name='log_acceso',
            name='fechaini',
            field=models.DateTimeField(default=0),
        ),
        migrations.AddField(
            model_name='log_acceso',
            name='id_modulo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log_acceso',
            name='id_usuario',
            field=models.IntegerField(default=0),
        ),
    ]
